### ISSUE TITLE
How to update the value of a key using UnorderedMap Class?

### ISSUE THREAD

**Issue by HighASG936** [braydenanderson2014/C-Arduino-Libraries#39]
Hi Brayden,

I'm trying to code a function that sweep along a String-String unordered map,
How can I update the value of an specific key?
What do you recommend?

I share to you my own approach in followed snipper:

```
#include "Strings.h"
#include "UnorderedMap.h"

typedef UnorderedMap<String, String> Reply;
Reply Replies;

void UpdateReplies()
{
     for (const auto& entry : Replies) 
     {
         // Update value of current key
          Replies. remove(entry.key);
          Replies.put(entry.key, "foo");
     }
}
```

Greetings!

**Comment by braydenanderson2014** [comment]
Hello, sorry it's been a minute since I've looked at this code so i have to double check how I implemented it. I should hopefully have an answer for you by the end of the day. If I am not mistaken you should be able to call put with the specified key and it should update the value but if it's not I'll run through the code and double check a few things. I might end up having to add a new function to control that scenario. I will let you know as soon as I know something.

**Comment by braydenanderson2014** [comment]
Hello, After Testing the Library, I have come to confirm that you can use the put method to override the original value of a key. I used the following code to test the library... In my test scenario, the Key "Hello" first prints out the value "Hello"... then when i call the put method with "Hello", "Goodbye"... It properly overrides the original value. It will then print "Goodbye"... 

#include <Arduino.h>
#include "UnorderedMap.h"

UnorderedMap<String, String> Mymap;

void setup(){
  Serial.begin(9600);
  Mymap.put("Hello", "Hello");
  Serial.println(Mymap.get("Hello"));
  Mymap.put("Hello", "Goodbye");
  Serial.println(Mymap.get("Hello"));

}

void loop(){

}

Since this is not an issue, This Issue request will be closed.

**Comment by HighASG936** [comment]
Great! 

 Thank you for your help, Brayden.

Greetings!

**Comment by braydenanderson2014** [comment]
If you have any more issues with any of my Libraries, Please do not hesitate to reach out. I am happy to research into my own code and fix anything that may need fixing. Thank you, Have a nice day!
